name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgstreamer-plugins-good1.0 libgstreamer-plugins-bad1.0 ffmpeg

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.6.x
        cache: true

    - name: Run Deno linter
      run: cd webapp && deno install && deno check

    - name: Check Rust
      run: cd preparer && cargo check --verbose

    - name: Check Rust formatting
      run: cd preparer && cargo fmt --check

    - name: Run Rust tests
      run: cd preparer && cargo test --verbose
